version: '2'

networks:
  test:

services:
  ca_org8:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org8.amazonbiobank.mooo.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=15054
    ports:
      - "15054:15054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/org8:/etc/hyperledger/fabric-ca-server
    container_name: ca.org8.amazonbiobank.mooo.com
    hostname: ca.org8.amazonbiobank.mooo.com
    networks:
      - test