version: '2'

networks:
  test:

services:
  ca_org7:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org7.amazonbiobank.mooo.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=14054
    ports:
      - "14054:14054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/org7:/etc/hyperledger/fabric-ca-server
    container_name: ca.org7.amazonbiobank.mooo.com
    hostname: ca.org7.amazonbiobank.mooo.com
    networks:
      - test